name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node
      uses: actions/setup-node@v1
    - name: npm install
      run: Install dependencies
    - name: Build and test
      run: npm clean-install
